# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.download_body_create import DownloadBodyCreate  # noqa: E501
from openapi_client.rest import ApiException

class TestDownloadBodyCreate(unittest.TestCase):
    """DownloadBodyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DownloadBodyCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.download_body_create.DownloadBodyCreate()  # noqa: E501
        if include_optional :
            return DownloadBodyCreate(
                node_ids = [
                    '0'
                    ]
            )
        else :
            return DownloadBodyCreate(
                node_ids = [
                    '0'
                    ],
        )

    def testDownloadBodyCreate(self):
        """Test DownloadBodyCreate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
