# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.activities_api import ActivitiesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestActivitiesApi(unittest.TestCase):
    """ActivitiesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.activities_api.ActivitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_activities_for_person(self):
        """Test case for list_activities_for_person

        List activities  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
