# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.audit_entry_paging_list import AuditEntryPagingList  # noqa: E501
from openapi_client.rest import ApiException

class TestAuditEntryPagingList(unittest.TestCase):
    """AuditEntryPagingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuditEntryPagingList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.audit_entry_paging_list.AuditEntryPagingList()  # noqa: E501
        if include_optional :
            return AuditEntryPagingList(
                pagination = openapi_client.models.pagination.Pagination(
                    count = 56, 
                    has_more_items = True, 
                    total_items = 56, 
                    skip_count = 56, 
                    max_items = 56, ), 
                entries = [
                    openapi_client.models.audit_entry_entry.AuditEntryEntry(
                        entry = openapi_client.models.audit_entry.AuditEntry(
                            id = '0', 
                            audit_application_id = '0', 
                            created_by_user = openapi_client.models.user_info.UserInfo(
                                display_name = '0', 
                                id = '0', ), 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            values = openapi_client.models.values.values(), ), )
                    ]
            )
        else :
            return AuditEntryPagingList(
        )

    def testAuditEntryPagingList(self):
        """Test AuditEntryPagingList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
