# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.person_network_paging_list import PersonNetworkPagingList  # noqa: E501
from openapi_client.rest import ApiException

class TestPersonNetworkPagingList(unittest.TestCase):
    """PersonNetworkPagingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PersonNetworkPagingList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.person_network_paging_list.PersonNetworkPagingList()  # noqa: E501
        if include_optional :
            return PersonNetworkPagingList(
                pagination = openapi_client.models.pagination.Pagination(
                    count = 56, 
                    has_more_items = True, 
                    total_items = 56, 
                    skip_count = 56, 
                    max_items = 56, ), 
                entries = [
                    openapi_client.models.person_network_entry.PersonNetworkEntry(
                        entry = openapi_client.models.person_network.PersonNetwork(
                            id = '0', 
                            home_network = True, 
                            is_enabled = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            paid_network = True, 
                            subscription_level = 'Free', 
                            quotas = [
                                openapi_client.models.network_quota.NetworkQuota(
                                    id = '0', 
                                    limit = 56, 
                                    usage = 56, )
                                ], ), )
                    ]
            )
        else :
            return PersonNetworkPagingList(
                pagination = openapi_client.models.pagination.Pagination(
                    count = 56, 
                    has_more_items = True, 
                    total_items = 56, 
                    skip_count = 56, 
                    max_items = 56, ),
                entries = [
                    openapi_client.models.person_network_entry.PersonNetworkEntry(
                        entry = openapi_client.models.person_network.PersonNetwork(
                            id = '0', 
                            home_network = True, 
                            is_enabled = True, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            paid_network = True, 
                            subscription_level = 'Free', 
                            quotas = [
                                openapi_client.models.network_quota.NetworkQuota(
                                    id = '0', 
                                    limit = 56, 
                                    usage = 56, )
                                ], ), )
                    ],
        )

    def testPersonNetworkPagingList(self):
        """Test PersonNetworkPagingList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
