# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.permissions_info import PermissionsInfo  # noqa: E501
from openapi_client.rest import ApiException

class TestPermissionsInfo(unittest.TestCase):
    """PermissionsInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PermissionsInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.permissions_info.PermissionsInfo()  # noqa: E501
        if include_optional :
            return PermissionsInfo(
                is_inheritance_enabled = True, 
                inherited = [
                    openapi_client.models.permission_element.PermissionElement(
                        authority_id = '0', 
                        name = '0', 
                        access_status = 'ALLOWED', )
                    ], 
                locally_set = [
                    openapi_client.models.permission_element.PermissionElement(
                        authority_id = '0', 
                        name = '0', 
                        access_status = 'ALLOWED', )
                    ], 
                settable = [
                    '0'
                    ]
            )
        else :
            return PermissionsInfo(
        )

    def testPermissionsInfo(self):
        """Test PermissionsInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
