# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services.   # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class AssociationBody(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'target_id': 'str',
        'assoc_type': 'str'
    }

    attribute_map = {
        'target_id': 'targetId',
        'assoc_type': 'assocType'
    }

    def __init__(self, target_id=None, assoc_type=None, local_vars_configuration=None):  # noqa: E501
        """AssociationBody - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._target_id = None
        self._assoc_type = None
        self.discriminator = None

        self.target_id = target_id
        self.assoc_type = assoc_type

    @property
    def target_id(self):
        """Gets the target_id of this AssociationBody.  # noqa: E501


        :return: The target_id of this AssociationBody.  # noqa: E501
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this AssociationBody.


        :param target_id: The target_id of this AssociationBody.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and target_id is None:  # noqa: E501
            raise ValueError("Invalid value for `target_id`, must not be `None`")  # noqa: E501

        self._target_id = target_id

    @property
    def assoc_type(self):
        """Gets the assoc_type of this AssociationBody.  # noqa: E501


        :return: The assoc_type of this AssociationBody.  # noqa: E501
        :rtype: str
        """
        return self._assoc_type

    @assoc_type.setter
    def assoc_type(self, assoc_type):
        """Sets the assoc_type of this AssociationBody.


        :param assoc_type: The assoc_type of this AssociationBody.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and assoc_type is None:  # noqa: E501
            raise ValueError("Invalid value for `assoc_type`, must not be `None`")  # noqa: E501

        self._assoc_type = assoc_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssociationBody):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssociationBody):
            return True

        return self.to_dict() != other.to_dict()
